apiVersion: v1
kind: ConfigMap
metadata:
  name: medtext-config
  namespace: medtext
  labels:
    app: medical-text-classification
    component: config
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "medtext_prod"
  RATE_LIMIT_REQUESTS: "50"
  RATE_LIMIT_WINDOW: "3600"
  ENABLE_SECURITY_HEADERS: "true"
  MAX_TEXT_LENGTH: "5000"
  MIN_TEXT_LENGTH: "1"
  LOG_REQUESTS: "true"
  LOG_SENSITIVE_DATA: "false"
  UVICORN_WORKERS: "4"
  UVICORN_MAX_WORKERS: "8"
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "30"
  DB_POOL_TIMEOUT: "30"
  MODEL_CACHE_SIZE: "1"
  MODEL_TIMEOUT: "300"
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  ENABLE_PROFILING: "false"
  ENABLE_DEBUG_ENDPOINTS: "false"
  MAX_REQUEST_SIZE: "10MB"
  MAX_CONCURRENT_REQUESTS: "100"
  REQUEST_TIMEOUT: "30"
  AUDIT_LOGGING: "true"
  DATA_RETENTION_DAYS: "365"
  GDPR_COMPLIANCE: "true"
  HIPAA_COMPLIANCE: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: medtext
  labels:
    app: medical-text-classification
    component: database
data:
  POSTGRES_DB: "medtext_prod"
  POSTGRES_USER: "medtext_user"
  POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: medtext
  labels:
    app: medical-text-classification
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "alert_rules.yml"
    
    scrape_configs:
      - job_name: 'medtext-api'
        static_configs:
          - targets: ['api-service:8000']
        metrics_path: '/metrics'
        scrape_interval: 30s
        scrape_timeout: 10s
      
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-service:5432']
        scrape_interval: 30s
      
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - medtext
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: medtext
  labels:
    app: medical-text-classification
    component: monitoring
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    
    [security]
    admin_user = admin
    cookie_secure = true
    cookie_samesite = strict
    disable_gravatar = true
    
    [users]
    allow_sign_up = false
    
    [analytics]
    reporting_enabled = false
    check_for_updates = false
    
    [log]
    mode = console
    level = info
