name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Combined quality checks and testing
  test-and-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.11"]  # Reduced matrix for efficiency

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_medical_text_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip install flake8 black isort mypy bandit ruff

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_medical_text_db" >> $GITHUB_ENV
        echo "TESTING=1" >> $GITHUB_ENV
        echo "LOG_LEVEL=WARNING" >> $GITHUB_ENV
        echo "MODEL_PATH=models" >> $GITHUB_ENV

    - name: Create mock model for testing
      run: |
        mkdir -p models
        echo '{"0": "Neurological & Cognitive Disorders", "1": "Cancers", "2": "Cardiovascular Diseases", "3": "Metabolic & Endocrine Disorders", "4": "Other Age-Related & Immune Disorders"}' > models/reverse_label_mapping.json
        echo '{"Neurological & Cognitive Disorders": 0, "Cancers": 1, "Cardiovascular Diseases": 2, "Metabolic & Endocrine Disorders": 3, "Other Age-Related & Immune Disorders": 4}' > models/label_mapping.json

    # Code Quality Checks
    - name: Run code quality checks
      run: |
        # Python linting
        ruff check src tests --output-format=github
        flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
        # Formatting checks
        black --check src tests
        isort --check-only src tests
        
        # Type checking
        mypy src --ignore-missing-imports --no-strict-optional
        
        # Security checks
        bandit -r src -f json -o bandit-report.json || true

    - name: Upload Bandit results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-security-report
        path: bandit-report.json

    # Testing
    - name: Run unit tests
      run: |
        python run_tests.py --unit --coverage

    - name: Run integration tests
      run: |
        python run_tests.py --integration --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          htmlcov/
          coverage.xml
          bandit-report.json

  # Docker Build and Security Scan
  build-and-scan:
    runs-on: ubuntu-latest
    needs: test-and-quality
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  # Test Docker Image
  test-image:
    runs-on: ubuntu-latest
    needs: build-and-scan
    if: github.event_name != 'pull_request'

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_medical_text_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Run container
        run: |
          docker run -d \
            --name test-api \
            --network host \
            -e DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_medical_text_db \
            -e TESTING=1 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
          # Wait for container to be healthy
          timeout 60 bash -c 'until docker exec test-api curl -f http://localhost:8000/health; do sleep 2; done'

      - name: Test API endpoints
        run: |
          # Test health endpoint
          curl -f http://localhost:8000/health
          
          # Test docs endpoint
          curl -f http://localhost:8000/docs
          
          # Test predict endpoint
          curl -X POST http://localhost:8000/predict \
            -H "Content-Type: application/json" \
            -d '{"text": "What are the symptoms of diabetes?"}' \
            | jq .

      - name: Check container logs
        if: always()
        run: |
          docker logs test-api

      - name: Stop container
        if: always()
        run: |
          docker stop test-api
          docker rm test-api

  # Deploy Application
  deploy:
    runs-on: ubuntu-latest
    needs: [test-image]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    environment:
      name: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tag
        id: image-tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Cloud Run (GCP)
        if: secrets.GCP_PROJECT_ID != ''
        id: deploy-gcp
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: medical-text-classifier-api
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
          region: us-central1
          credentials: ${{ secrets.GCP_SA_KEY }}
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}
            MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }}
            MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}
            MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}

      - name: Run smoke tests
        run: |
          # Wait for deployment to be ready
          sleep 30
          
          # Test health endpoint
          DEPLOY_URL="${{ steps.deploy-gcp.outputs.url || secrets.DEPLOY_URL }}"
          curl -f ${DEPLOY_URL}/health || exit 1
          
          # Test predict endpoint
          curl -X POST ${DEPLOY_URL}/predict \
            -H "Content-Type: application/json" \
            -d '{"text": "What are the symptoms of diabetes?"}' \
            | jq .

      - name: Notify deployment status
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            Deployment to ${{ github.event.inputs.environment || 'staging' }} ${{ job.status }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}